use_frameworks!

platform :ios, '9.0'

target 'XLRootProject_Example' do
  pod 'XLRootProject', :path => '../'

  target 'XLRootProject_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
